name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Stop and Remove Docker Containers
        run: docker-compose -f ./Docker-compose.yml down -v

      - name: Build Docker Image
        run: docker-compose -f ./Docker-compose.yml build --no-cache=false

      - name: Start Docker Containers
        run: docker-compose -f ./Docker-compose.yml up -d

      - name: Wait for SQL Server
        run: sleep 5s

      - name: Execute Entry Point Script
        run: |
          docker-compose -f ./Docker-compose.yml exec -T sqlserver /bin/bash -c '/scripts/entrypoint.sh'
          exit_status=$?
          if [ $exit_status -ne 0 ]; then
            echo "Entry point script failed with exit code $exit_status"
            exit $exit_status
          fi

      - name: Run Tests
        run: docker-compose -f ./Docker-compose.yml exec -T sqlserver /bin/bash -c 'pytest /path/to/tests'

      - name: Stop Docker Containers
        run: docker-compose -f ./Docker-compose.yml down -v
