name: Continuous Integration

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Ubuntu as the operating system for the job

    steps:
      # Checkout the repository to the runner
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform builds (optional but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build the Docker image using docker-compose
      - name: Build Docker Image
        run: docker-compose -f ./Docker-compose.yml build

      # Run tests inside the Docker container
      - name: Run Tests
        run: |
          docker-compose -f ./Docker-compose.yml up -d  # Start the containers in detached mode
          # Add waiting logic here before running tests if needed
          sleep 30s  # Example: wait for 30 seconds for containers to start (adjust as necessary)
          docker-compose -f ./Docker-compose.yml exec sqlserver /bin/bash -c 'chmod +x /scripts/entrypoint.sh && /scripts/entrypoint.sh'

      # Perform additional steps if needed, such as publishing test results or artifacts

      # Stop and clean up the Docker containers after tests
      - name: Stop Docker Containers
        run: docker-compose -f ./Docker-compose.yml down
